[package]
name = "fvim"
version = "0.5.0"
edition = "2021"
publish = false

[dependencies]
crossterm = "=0.29.0"
regex = { version = "=1.13.1", default-features = false, features = ["std", "perf", "unicode-perl", "unicode-case"] }
unicode-width = "=0.2.2"
mlua = { version = "=0.12.1", default-features = false, features = ["lua54", "vendored"] }

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1
strip = true
